[package]
name = 'fcl'
version = '0.1.0'
edition = '2021'

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = [ 'staticlib' ]

[dependencies]
extendr-api = '0.2.0'
financial="1.1.3"
chrono="0.4.19"
